version: '3, or 4'

services:
  back-end:
    build:
      context: ./task4/back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    ports:
      - "5252"

  front-end:
    build:
      context: ./task4/front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    ports:
      - "9000"

  proxy:
    build:
      context: ./task5/proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"