version: '3, or 4'

services:
  back-end:
    build:
      context: ./task4/back-end
      dockerfile: Dockerfile
    image: soft-pinko-back-end:task4
    ports:
      - "5252:5252"

  front-end:
    build:
      context: ./task4/front-end
      dockerfile: Dockerfile
    image: soft-pinko-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
      - back-end